name: Run Java Program
on:
  push:
    branches:
      - main
jobs:
  run-java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "23"
      - name: compile Java Program
        run: javac Hello.java
      - name: Run Hello
        run: java Hello
